# Generated by Django 3.2.8 on 2021-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
